### ISSUE TITLE
delete code pls

### ISSUE THREAD

**Issue by maxchrr** [MatthieuProjects/AutoFeur#1]

**Comment by MatthieuCoder** [comment]
Dear Sir,

Please stop interacting with this project in a matter that does not make sense,
We will be getting in touch with the legal authorities to make your embarrassing harassing attempts be taken care of.

Now please let me allow myself to let wish you a great day.

Yours faithfully,
Matthieu

**Comment by maxchrr** [comment]
Aww, it's so sweet of you to think of me! (´꒳`) Wishing you a day filled with happiness and sweetness, just like a little kitten playing with a ball of yarn! 🐱💕

**Comment by GabeeTheFinch** [comment]
Awww we rarely see such sweetness on the internet!!!

**Comment by ncs-pl** [comment]
![Omg GNU:Linux is Hot](https://github.com/MatthieuProjects/AutoFeur/assets/34602094/6ef4b7d6-245e-4b64-923e-f59a524eeb4c)

**Comment by GabeeTheFinch** [comment]
![image](https://github.com/MatthieuProjects/AutoFeur/assets/45103833/776f7559-ed18-4fda-b1bb-fdfe8403f310)

**Comment by maxchrr** [comment]
![image](https://github.com/MatthieuProjects/AutoFeur/assets/47574874/dff3952d-a333-4b41-a6c6-79448ac17cc0)

**Comment by ncs-pl** [comment]
![image](https://github.com/MatthieuProjects/AutoFeur/assets/34602094/bbdc243f-5df4-4777-ae27-49ecc48b91b6)

**Comment by maxchrr** [comment]
![image](https://github.com/MatthieuProjects/AutoFeur/assets/47574874/1b424725-e6c6-40c4-89df-02fe0abbf49a)
